AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  lambdaFunctions

  SAM Template for OSU Search lambda functions

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Resources:
  CallApigeeApiFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: callApigeeApi/
      Handler: index.handler
      Runtime: nodejs8.10
      Events:
        Locations:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /locations
            Method: get

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  CallApigeeApi:
    Description: 'API Gateway endpoint URL for Prod stage for CallApigeeApi function'
    Value: !Sub 'https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/prod/locations/'
  CallApigeeApiFunction:
    Description: 'CallApigeeApi Lambda Function ARN'
    Value: !GetAtt CallApigeeApiFunction.Arn
  CallApigeeApiFunctionIamRole:
    Description: 'Implicit IAM Role created for Locations function'
    Value: !GetAtt CallApigeeApiFunctionRole.Arn
