name: Build and Push Server Application to AWS PRODUCTION
on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: yarn install, test
        run: |
          yarn install --frozen-lockfile
          yarn run test
        env:
          SKIP_PREFLIGHT_CHECK: true
          FONTAWESOME_TOKEN: ${{ secrets.FONTAWESOME_TOKEN }}
  build:
    needs: test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Build client
        run: |
          yarn install --frozen-lockfile
          yarn run build
        env:
          SKIP_PREFLIGHT_CHECK: true
          FONTAWESOME_TOKEN: ${{ secrets.FONTAWESOME_TOKEN }}
      - name: Copy client to S3 and flush Cloudfront cache for PRODUCTION
        run: |
          COMMIT_LINK=https://github.com/$GITHUB_REPOSITORY/commit/$GITHUB_SHA
          COMMIT_MESSAGE=$(git log --format=%B -n 1 $GITHUB_SHA | cat -)
          POST_DATA="{\"@type\": \"MessageCard\", \"@context\": \"http://schema.org/extensions\", \"themeColor\": \"D600D2\", \"summary\": \"Search Production FrontEnd Deployment\", \"sections\": [{ \"activityTitle\": \"Search: production\", \"activitySubtitle\": \"Status: DEPLOYMENT_STARTED, Message: $COMMIT_MESSAGE $COMMIT_LINK\", \"markdown\": false }] }"
          curl -d "${POST_DATA}" -H "Content-Type: application/json" -X POST ${{ secrets.TEAMS_WAMS_CICD_HOOK_URL }}
          s3_bucket_url=s3://${{ secrets.AWS_S3_BUCKET_URL_PREFIX }}-prod
          aws s3 sync build ${s3_bucket_url}
          aws cloudfront create-invalidation --distribution-id ${{ secrets.AWS_CLOUDFRONT_DISTRIBUTION_ID_PRODUCTION }} --paths /index.html
          POST_DATA="{\"@type\": \"MessageCard\", \"@context\": \"http://schema.org/extensions\", \"themeColor\": \"D600D2\", \"summary\": \"Search Production Frontend Deployment\", \"sections\": [{ \"activityTitle\": \"Search: production\", \"activitySubtitle\": \"Status: DEPLOYMENT_COMPLETE, Message: $COMMIT_MESSAGE $COMMIT_LINK\", \"markdown\": false }] }"
          curl -d "${POST_DATA}" -H "Content-Type: application/json" -X POST ${{ secrets.TEAMS_WAMS_CICD_HOOK_URL }}
        env:
          FONTAWESOME_TOKEN: ${{ secrets.FONTAWESOME_TOKEN }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}
